# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/kl/ane

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/kl/ane

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/kl/ane/CMakeFiles /data/kl/ane//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/kl/ane/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /data/kl/ane/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ane_object

# Build rule for target.
ane_object: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ane_object
.PHONY : ane_object

# fast build rule for target.
ane_object/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ane_object.dir/build.make CMakeFiles/ane_object.dir/build
.PHONY : ane_object/fast

#=============================================================================
# Target rules for targets named ane

# Build rule for target.
ane: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ane
.PHONY : ane

# fast build rule for target.
ane/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ane.dir/build.make CMakeFiles/ane.dir/build
.PHONY : ane/fast

#=============================================================================
# Target rules for targets named ane-disasm

# Build rule for target.
ane-disasm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ane-disasm
.PHONY : ane-disasm

# fast build rule for target.
ane-disasm/fast:
	$(MAKE) $(MAKESILENT) -f tools/ane-disasm/CMakeFiles/ane-disasm.dir/build.make tools/ane-disasm/CMakeFiles/ane-disasm.dir/build
.PHONY : ane-disasm/fast

src/libane/hwx.o: src/libane/hwx.cpp.o
.PHONY : src/libane/hwx.o

# target to build an object file
src/libane/hwx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ane_object.dir/build.make CMakeFiles/ane_object.dir/src/libane/hwx.cpp.o
.PHONY : src/libane/hwx.cpp.o

src/libane/hwx.i: src/libane/hwx.cpp.i
.PHONY : src/libane/hwx.i

# target to preprocess a source file
src/libane/hwx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ane_object.dir/build.make CMakeFiles/ane_object.dir/src/libane/hwx.cpp.i
.PHONY : src/libane/hwx.cpp.i

src/libane/hwx.s: src/libane/hwx.cpp.s
.PHONY : src/libane/hwx.s

# target to generate assembly for a file
src/libane/hwx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ane_object.dir/build.make CMakeFiles/ane_object.dir/src/libane/hwx.cpp.s
.PHONY : src/libane/hwx.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ane"
	@echo "... ane-disasm"
	@echo "... ane_object"
	@echo "... src/libane/hwx.o"
	@echo "... src/libane/hwx.i"
	@echo "... src/libane/hwx.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /data/kl/ane/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

